### ISSUE TITLE
Lassú internetkapcsolat esetén dupla Footer jelenik meg

### ISSUE THREAD

**Issue by dzsak** [flowacademyhu/piac-app#105]
Lassú internetkapcsolat esetén dupla Footer jelenik meg pl az adott piachoz tartozó áruslista betöltésekor, például, ha a stagingen rákattintunk a 4 árusos Bödön piacra (most ez a linkje: https://stage.felpenzzel.hu/piacok/1).

**Comment by taritamas89** [comment]
@dzsak ezzel mizu? miért került reviewba?
