### ISSUE TITLE
Kerek profilképek módosítási igényei

### ISSUE THREAD

**Issue by sandorforgo** [flowacademyhu/piac-app#149]
Ahol a kerek profilképek vannak (legyen akár Piac, akár Árus), legyenek igazak a következők:
- [x] mindig dark gray a border
- [x] legyen fix méretük, 100x100 pixel, így amíg nem tölt be az oldal akkor se ugrik (ez alól egyetlen kivétel van, a Piachoz tartozó Árusok oldala, mivel ott a header 100 pixel, tehát itt a logo 80x80-as legyen)
- [x] ha nincs kép beállítva, akkor rakjunk be egy fallback/placeholder képet

**Comment by 6uliver** [comment]
Csatoltam a placeholder képeket.

![arus](https://user-images.githubusercontent.com/7010495/140438421-99216f69-adcd-4d8b-9d8d-b06c5f168986.png)
![piac](https://user-images.githubusercontent.com/7010495/140438423-ea5354cb-d042-4af9-9ba3-fa8240210019.png)
