### ISSUE TITLE
Adminisztrátorok számának 1-re korlátozása

### ISSUE THREAD

**Issue by sandorforgo** [flowacademyhu/piac-app#37]
Epic: #22 
Feladat: Miután az első felhasználó regisztrált, más már ne tudjon regisztrálni.

**Comment by kalmargabor92** [comment]
@kovarik85 - ez már készen van nem?

**Comment by kovarik85** [comment]
Igen, ahogy beszéltük korábban, maga a SendGrid folyamat úgy lett kialakítva, hogy egy admin lesz, és az emailben kiküldött random String jelszó is csak egyszer használható
